import type { HintId } from "../../domain/hints";

export const curatedHints: Record<string, HintId> = {
  "ask around": "ask-around-ripples",
  "back up": "back-up-layers",
  "break down": "break-down-split",
  "bring back": "bring-back-orbit",
  "call off": "call-off-cross",
  "carry on": "carry-on-path",
  "catch up": "catch-up-steps",
  "check in": "check-in-gate",
  "cheer up": "cheer-up-sun",
  "give up": "give-up-flag",
  "get along": "get-along-bridge",
  "get away": "get-away-horizon",
  "get back": "get-back-loop",
  "get over": "get-over-arch",
  "look after": "look-after-orbit",
  "look for": "look-for-beacon",
  "look forward to": "look-forward-arrow",
  "make up": "make-up-join",
  "pick up": "pick-up-rise",
  "put off": "put-off-pause",
  "a piece of cake": "a-piece-of-cake-easy",
  "absolutely necessary": "absolutely-necessary-essential",
  "achieve": "achieve-achieve-achievement",
  "act": "act-act-action",
  "advantage of": "advantage-of-benefit",
  "afraid of": "afraid-of-feeling-fear",
  "agree": "agree-agree-agreement",
  "agree with": "agree-with-same-opinion",
  "amaze": "amaze-amaze-amazement",
  "angry with": "angry-with-feeling-angry",
  "announce": "announce-announce-announcement",
  "answer to": "answer-to-response",
  "apologize for": "apologize-for-say-sorry",
  "appear": "appear-appear-appearance",
  "apply": "apply-apply-application",
  "apply for": "apply-for-formally-request",
  "argue": "argue-argue-argument",
  "arrange": "arrange-arrange-arrangement",
  "ask for": "ask-for-request",
  "ask out": "ask-out-invite-date",
  "attend": "attend-attend-attendance",
  "attract": "attract-attract-attraction",
  "avoid": "avoid-avoid-avoidance",
  "back down": "back-down-stop-defending",
  "bad at": "bad-at-unable-well",
  "be": "be-exist-present",
  "become": "become-start",
  "begin": "begin-start",
  "believe": "believe-believe-belief",
  "believe in": "believe-in-faith",
  "belong to": "belong-to-owned",
  "bend": "bend-curve-lean",
  "benefit": "benefit-benefit-beneficial",
  "better late than never": "better-late-than-never-better-late",
  "bite": "bite-cut-teeth",
  "bleed": "bleed-lose-blood",
  "blow": "blow-move-air",
  "blow up": "blow-up-explode-inflate",
  "break": "break-separate-pieces",
  "break in": "break-in-enter-building",
  "break into": "break-into-enter-place",
  "break out": "break-out-start-suddenly",
  "break the ice": "break-the-ice-people-feel",
  "break through": "break-through-important-advance",
  "break up": "break-up-end-relationship",
  "bring": "bring-carry-here",
  "bring about": "bring-about-cause-happen",
  "bring in": "bring-in-introduce-earn",
  "bring out": "bring-out-quality-noticeable",
  "bring up": "bring-up-mention-topic",
  "brush up on": "brush-up-on-improve-skill",
  "build": "build-construct",
  "build up": "build-up-increase-develop",
  "burn": "burn-fire",
  "buy": "buy-money",
  "call back": "call-back-return-phone",
  "call for": "call-for-require-demand",
  "call it a day": "call-it-a-day-stop-working",
  "call on": "call-on-ask-speak",
  "calm down": "calm-down-less-upset",
  "care": "care-care-careful",
  "care about": "care-about-consider-important",
  "carry out": "carry-out-complete-task",
  "catch": "catch-hold",
  "catch on": "catch-on-understand-popular",
  "check out": "check-out-leave-hotel",
  "check up on": "check-up-on-sure-all",
  "choose": "choose-pick",
  "clean up": "clean-up-place-clean",
  "clear up": "clear-up-clear-tidy",
  "close friend": "close-friend-good-friend",
  "closely related": "closely-related-strongly-connected",
  "come": "come-move-here",
  "come across": "come-across-find-chance",
  "come along": "come-along-accompany-progress",
  "come back": "come-back-return",
  "come down with": "come-down-with-ill",
  "come in": "come-in-enter",
  "come on": "come-on-encourage-tell",
  "come out": "come-out-published-released",
  "come over": "come-over-visit-their",
  "come up": "come-up-happen-unexpectedly",
  "come up with": "come-up-with-think-idea",
  "common mistake": "common-mistake-error-people",
  "communicate": "communicate-communicate-communication",
  "compete": "compete-compete-competition",
  "complain about": "complain-about-say-unhappy",
  "complete": "complete-complete-completion",
  "completely different": "completely-different-totally-unlike",
  "concentrate on": "concentrate-on-all-attention",
  "confuse": "confuse-confuse-confusion",
  "connect": "connect-connect-connection",
  "consider": "consider-consider-consideration",
  "consist of": "consist-of-made",
  "cost": "cost-price",
  "cost an arm and a leg": "cost-an-arm-and-a-leg-expensive",
  "count on": "count-on-rely",
  "create": "create-create-creation",
  "cut": "cut-divide-knife",
  "cut back on": "cut-back-on-reduce-amount",
  "cut down on": "cut-down-on-reduce-amount",
  "cut off": "cut-off-stop-supply",
  "cut out": "cut-out-remove-stop",
  "deal with": "deal-with-action-solve",
  "decide": "decide-decide-decision",
  "deep sleep": "deep-sleep-sound-sleep",
  "deeply worried": "deeply-worried-worried",
  "depend on": "depend-on-decided",
  "describe": "describe-describe-description",
  "develop": "develop-develop-development",
  "differ": "differ-differ-difference",
  "difference between": "difference-between-way-which",
  "different from": "different-from-same",
  "dig": "dig-hole",
  "do": "do-perform",
  "do a good job": "do-a-good-job-perform-task",
  "do business": "do-business-conduct-commercial",
  "do damage": "do-damage-cause-harm",
  "do exercise": "do-exercise-physical-exercise",
  "do homework": "do-homework-complete-schoolwork",
  "do over": "do-over-again",
  "do research": "do-research-study-subject",
  "do someone a favor": "do-someone-a-favor-helpful",
  "do the dishes": "do-the-dishes-wash-dishes",
  "do the shopping": "do-the-shopping-buy-food",
  "do without": "do-without-manage-without",
  "do your best": "do-your-best-try-hard",
  "draw": "draw-picture",
  "dress up": "dress-up-wear-smart",
  "drink": "drink-swallow-liquid",
  "drive": "drive-control-car",
  "drop by": "drop-by-visit-briefly",
  "drop off": "drop-off-place-leave",
  "drop out": "drop-out-leave-course",
  "easier said than done": "easier-said-than-done-difficult-talk",
  "eat": "eat-consume-food",
  "eat out": "eat-out-eat-restaurant",
  "educate": "educate-educate-education",
  "employ": "employ-employ-employment",
  "encourage": "encourage-encourage-encouragement",
  "end up": "end-up-finally-particular",
  "enjoy": "enjoy-enjoy-enjoyment",
  "entertain": "entertain-entertain-entertainment",
  "excite": "excite-excite-excitement",
  "exist": "exist-exist-existence",
  "expect": "expect-expect-expectation",
  "experience with": "experience-with-knowledge-gained",
  "explain": "explain-explain-explanation",
  "express": "express-express-expression",
  "extremely difficult": "extremely-difficult-difficult",
  "face up to": "face-up-to-confront-difficult",
  "fail": "fail-fail-failure",
  "fall": "fall-drop-down",
  "fall apart": "fall-apart-break-pieces",
  "fall behind": "fall-behind-fail",
  "fall for": "fall-for-fall-love",
  "fall out": "fall-out-argue-stop",
  "famous for": "famous-for-known-people",
  "fast food": "fast-food-food-prepared",
  "feed": "feed-food",
  "feel": "feel-sensation",
  "fight": "fight-struggle-against",
  "figure out": "figure-out-understand-solve",
  "fill in": "fill-in-complete-form",
  "fill out": "fill-out-complete-form",
  "fill up": "fill-up-full",
  "find": "find-discover",
  "find out": "find-out-discover-information",
  "fly": "fly-travel-air",
  "focus on": "focus-on-special-attention",
  "forget": "forget-fail-remember",
  "forgive": "forgive-stop-blaming",
  "freeze": "freeze-turn-ice",
  "friend": "friend-friend-friendship",
  "fully aware": "fully-aware-completely-conscious",
  "get": "get-obtain",
  "get across": "get-across-communicate-idea",
  "get ahead": "get-ahead-progress-succeed",
  "get around": "get-around-move-place",
  "get around to": "get-around-to-finally-find",
  "get away with": "get-away-with-wrong-without",
  "get better": "get-better-improve",
  "get by": "get-by-manage-what",
  "get down to": "get-down-to-start-doing",
  "get in": "get-in-enter-arrive",
  "get married": "get-married-someone-s-husband",
  "get off": "get-off-leave-bus",
  "get on": "get-on-board-vehicle",
  "get out": "get-out-leave-place",
  "get out of hand": "get-out-of-hand-impossible-control",
  "get ready": "get-ready-prepare-yourself",
  "get rid of": "get-rid-of-remove-throw",
  "get the hang of it": "get-the-hang-of-it-learn-how",
  "get through": "get-through-finish-survive",
  "get together": "get-together-meet-socially",
  "get up": "get-up-rise-bed",
  "give": "give-hand",
  "give away": "give-away-free-reveal",
  "give back": "give-back-return-its",
  "give in": "give-in-finally-agree",
  "give out": "give-out-distribute-used",
  "give someone a hand": "give-someone-a-hand-help",
  "go": "go-move-travel",
  "go ahead": "go-ahead-proceed-start",
  "go ahead with": "go-ahead-with-continue-plan",
  "go away": "go-away-leave",
  "go back": "go-back-return-place",
  "go off": "go-off-ring-explode",
  "go on": "go-on-continue-happen",
  "go out": "go-out-leave-home",
  "go over": "go-over-review-carefully",
  "go the extra mile": "go-the-extra-mile-effort-expected",
  "go through": "go-through-experience-examine",
  "go without": "go-without-manage-without",
  "good at": "good-at-able-well",
  "great opportunity": "great-opportunity-good-chance",
  "grow": "grow-increase",
  "grow up": "grow-up-adult",
  "hand in": "hand-in-work-documents",
  "hand out": "hand-out-distribute",
  "hang": "hang-suspend",
  "hang in there": "hang-in-there-continue-despite",
  "hang on": "hang-on-wait-short",
  "hang out": "hang-out-spend-time",
  "hang up": "hang-up-end-phone",
  "hard work": "hard-work-work-requires",
  "have": "have-possess",
  "have a chance": "have-a-chance-opportunity",
  "have a conversation": "have-a-conversation-talk",
  "have a good time": "have-a-good-time-enjoy-yourself",
  "hear": "hear-perceive-sound",
  "heavy rain": "heavy-rain-rain-falls",
  "help": "help-help-helpful",
  "hide": "hide-conceal",
  "high probability": "high-probability-strong-chance",
  "highly recommended": "highly-recommended-recommended-strongly",
  "hit": "hit-strike",
  "hit the nail on the head": "hit-the-nail-on-the-head-say-exactly",
  "hold": "hold-grasp",
  "hold back": "hold-back-restrain-stop",
  "hold on": "hold-on-wait-hold",
  "hold on to": "hold-on-to-hold-tightly",
  "hurry up": "hurry-up-quickly",
  "hurt": "hurt-cause-pain",
  "imagine": "imagine-imagine-imagination",
  "improve": "improve-improve-improvement",
  "in the same boat": "in-the-same-boat-same-difficult",
  "increase in": "increase-in-rise-amount",
  "inform": "inform-inform-information",
  "instruct": "instruct-instruct-instruction",
  "intend": "intend-intend-intention",
  "interest": "interest-interest-interesting",
  "interested in": "interested-in-wanting-know",
  "invite": "invite-invite-invitation",
  "keep": "keep-retain",
  "keep an eye on": "keep-an-eye-on-watch-carefully",
  "keep away": "keep-away-stay-distance",
  "keep off": "keep-off-stay-off",
  "keep on": "keep-on-continue-doing",
  "keep track of": "keep-track-of-record",
  "keep up": "keep-up-continue-same",
  "keep up with": "keep-up-with-stay-informed",
  "kick off": "kick-off-begin",
  "know": "know-knowledge",
  "laugh at": "laugh-at-fun",
  "lay": "lay-down",
  "lead": "lead-guide",
  "learn the hard way": "learn-the-hard-way-learn-unpleasant",
  "leave": "leave-away",
  "leave behind": "leave-behind-forget-place",
  "leave out": "leave-out-omit",
  "lend": "lend-temporarily",
  "let": "let-allow",
  "let down": "let-down-disappoint",
  "let in": "let-in-allow-enter",
  "lie": "lie-rest-horizontally",
  "light": "light-illuminate",
  "listen to": "listen-to-attention-sound",
  "live up to": "live-up-to-meet-expectations",
  "log in": "log-in-sign-computer",
  "log out": "log-out-sign-out",
  "look around": "look-around-explore-look",
  "look at": "look-at-direct-eyes",
  "look back on": "look-back-on-think-about",
  "look into": "look-into-investigate",
  "look out": "look-out-careful",
  "look up": "look-up-search-information",
  "look up to": "look-up-to-admire-respect",
  "lose": "lose-misplace",
  "make": "make-create",
  "make a choice": "make-a-choice-choose-options",
  "make a decision": "make-a-decision-choose-what",
  "make a difference": "make-a-difference-important-effect",
  "make a mistake": "make-a-mistake-incorrectly",
  "make a promise": "make-a-promise-say",
  "make an effort": "make-an-effort-try-hard",
  "make friends": "make-friends-friends-people",
  "make money": "make-money-earn-money",
  "make out": "make-out-see-understand",
  "make plans": "make-plans-arrange-future",
  "make progress": "make-progress-improve-advance",
  "make up for": "make-up-for-compensate",
  "make up your mind": "make-up-your-mind-decision",
  "manage": "manage-manage-management",
  "mean": "mean-signify",
  "meet": "meet-encounter",
  "miss the point": "miss-the-point-fail-understand",
  "motivate": "motivate-motivate-motivation",
  "move in": "move-in-start-living",
  "move out": "move-out-stop-living",
  "need for": "need-for-requirement",
  "no big deal": "no-big-deal-important-serious",
  "on the right track": "on-the-right-track-thinking-acting",
  "on the same page": "on-the-same-page-share-same",
  "once in a blue moon": "once-in-a-blue-moon-rarely",
  "organize": "organize-organize-organization",
  "out of the blue": "out-of-the-blue-unexpectedly",
  "pass away": "pass-away-die",
  "pass out": "pass-out-faint-distribute",
  "pay": "pay-money",
  "pay back": "pay-back-return-money",
  "pay for": "pay-for-money",
  "perfectly normal": "perfectly-normal-entirely-usual",
  "perform": "perform-perform-performance",
  "permit": "permit-permit-permission",
  "pick out": "pick-out-choose",
  "please": "please-pleasure-pleasant",
  "pleased with": "pleased-with-satisfied",
  "point out": "point-out-draw-attention",
  "pollute": "pollute-pollute-pollution",
  "predict": "predict-predict-prediction",
  "prefer": "prefer-prefer-preference",
  "prepare": "prepare-prepare-preparation",
  "prevent": "prevent-prevent-prevention",
  "problem with": "problem-with-difficulty-involving",
  "produce": "produce-produce-production",
  "protect": "protect-protect-protection",
  "proud of": "proud-of-pleased-about",
  "pull someone's leg": "pull-someone-s-leg-joke-trying",
  "put": "put-place",
  "put aside": "put-aside-save-reserve",
  "put away": "put-away-its-proper",
  "put back": "put-back-return-its",
  "put down": "put-down-surface-write",
  "put forward": "put-forward-suggest-idea",
  "put on": "put-on-dress-switch",
  "put out": "put-out-extinguish-fire",
  "put together": "put-together-assemble",
  "put up with": "put-up-with-tolerate-unpleasant",
  "quit": "quit-leave-stop",
  "react": "react-react-reaction",
  "read": "read-look-words",
  "ready for": "ready-for-prepared",
  "reason for": "reason-for-cause",
  "refer to": "refer-to-mention-describe",
  "relate": "relate-relate-relation",
  "relationship with": "relationship-with-connection",
  "relax": "relax-relax-relaxation",
  "rely": "rely-rely-reliability",
  "rely on": "rely-on-depend-trust",
  "respond": "respond-respond-response",
  "responsible for": "responsible-for-having-duty",
  "ride": "ride-travel",
  "ring": "ring-bell-sound",
  "ring a bell": "ring-a-bell-familiar",
  "rise": "rise-sun-rose",
  "rule out": "rule-out-decide-impossible",
  "run": "run-move-fast",
  "run into": "run-into-meet-chance",
  "run out": "run-out-used",
  "run out of": "run-out-of-we-ve-run",
  "satisfy": "satisfy-satisfy-satisfaction",
  "say": "say-speak-words",
  "see": "see-perceive-eyes",
  "see eye to eye": "see-eye-to-eye-agree-completely",
  "sell": "sell-exchange-money",
  "send": "send-dispatch",
  "serious problem": "serious-problem-important-difficult",
  "set": "set-adjust",
  "set off": "set-off-begin-journey",
  "set up": "set-up-arrange-install",
  "settle down": "settle-down-begin-living",
  "shake": "shake-move-quickly",
  "shine": "shine-light",
  "shoot": "shoot-fire",
  "show": "show-display",
  "show off": "show-off-try-impress",
  "show up": "show-up-arrive-appear",
  "shut": "shut-close",
  "shut down": "shut-down-turn-off",
  "similar to": "similar-to-almost-same",
  "sing": "sing-music-voice",
  "sink": "sink-under-water",
  "sit": "sit-seat",
  "sit down": "sit-down-move-sitting",
  "sleep": "sleep-rest-night",
  "slide": "slide-glide",
  "slow down": "slow-down-move-less",
  "so far, so good": "so-far-so-good-things-going",
  "solution to": "solution-to-answer-problem",
  "solve": "solve-solve-solution",
  "sort out": "sort-out-solve-organize",
  "speak": "speak-talk",
  "speak of the devil": "speak-of-the-devil-said-when",
  "speak up": "speak-up-speak-loudly",
  "spend": "spend-use-money",
  "split": "split-divide",
  "stand": "stand-upright",
  "stand for": "stand-for-represent-mean",
  "stand up": "stand-up-rise-standing",
  "stay up": "stay-up-remain-awake",
  "steal": "steal-without-permission",
  "stick": "stick-attach",
  "stick to": "stick-to-continue-following",
  "strike": "strike-hit",
  "strong coffee": "strong-coffee-coffee-powerful",
  "strongly recommended": "strongly-recommended-advised-emphasis",
  "succeed": "succeed-succeed-success",
  "suffer from": "suffer-from-experience-illness",
  "suggest": "suggest-suggest-suggestion",
  "surprise": "surprise-surprise-surprising",
  "surprised by/at": "surprised-by-at-feeling-surprised",
  "swear": "swear-promise",
  "sweep": "sweep-clean-broom",
  "swim": "swim-move-water",
  "take": "take-carry-remove",
  "take a break": "take-a-break-stop-working",
  "take a look": "take-a-look-look-briefly",
  "take after": "take-after-resemble-older",
  "take away": "take-away-remove-carry",
  "take back": "take-back-return-withdraw",
  "take in": "take-in-understand-absorb",
  "take it easy": "take-it-easy-relax-worry",
  "take notes": "take-notes-write-important",
  "take off": "take-off-leave-ground",
  "take on": "take-on-accept-work",
  "take out": "take-out-remove-somewhere",
  "take over": "take-over-control-responsibility",
  "take responsibility": "take-responsibility-accept-duty",
  "take up": "take-up-start-hobby",
  "take your time": "take-your-time-hurry",
  "talk about": "talk-about-discuss",
  "talk over": "talk-over-discuss-carefully",
  "teach": "teach-lessons",
  "tear": "tear-rip",
  "tell": "tell-inform",
  "the last straw": "the-last-straw-final-problem",
  "think": "think-opinion",
  "think about": "think-about-consider",
  "think outside the box": "think-outside-the-box-think-creatively",
  "think over": "think-over-consider-carefully",
  "throw": "throw-launch",
  "throw away": "throw-away-rid-putting",
  "time flies": "time-flies-time-passes",
  "tired of": "tired-of-longer-wanting",
  "try on": "try-on-clothing-see",
  "turn around": "turn-around-turn-face",
  "turn down": "turn-down-refuse-reduce",
  "turn into": "turn-into-different",
  "turn off": "turn-off-switch-off",
  "turn on": "turn-on-switch",
  "turn up": "turn-up-arrive-unexpectedly",
  "under the weather": "under-the-weather-feeling-slightly",
  "understand": "understand-comprehend",
  "up in the air": "up-in-the-air-decided-yet",
  "use": "use-use-user",
  "vary": "vary-vary-variety",
  "wait for": "wait-for-stay-until",
  "wake": "wake-stop-sleeping",
  "wake up": "wake-up-stop-sleeping",
  "warm up": "warm-up-warmer-prepare",
  "watch out": "watch-out-careful",
  "wear": "wear-clothes",
  "wear out": "wear-out-damaged-use",
  "widely available": "widely-available-available-places",
  "win": "win-victorious",
  "wonder": "wonder-wonder-wonderful",
  "work on": "work-on-spend-time",
  "work out": "work-out-exercise-solve",
  "worried about": "worried-about-anxious-about",
  "worth a shot": "worth-a-shot-worth-trying",
  "write": "write-words",
  "write down": "write-down-record-writing",
};
